use_frameworks!

target 'LVUITestUtils_Example' do
  pod 'LVUITestUtilsServer', :path => '../'
  pod 'Swifter'
  pod 'SimulatorStatusMagic'

  target 'LVUITestUtils_ExampleUITests' do
      inherit! :search_paths
      pod 'LVUITestUtils', :path => '../'
  end
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '3.0'
          end
      end
  end
end
